set -g mouse on
setw -g mode-keys vi
set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# Automatic window renaming
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_command}: #{b:pane_current_path}'

# The space between the items in the window list
setw -g window-status-separator ' | '
